### ISSUE TITLE
Water temperature not consistently updated

### ISSUE THREAD

**Issue by vharten** [msvisser/remeha_home#39] opened 2023-11-16 11:54 UTC
Hi,

I see that the water temperature is not consistently updated, sometimes it. Sometimes it updates every 5 minutes, but most of the times the value stays the same for a few hours, while in fact it has been changed more often.

See attachment.
![Water Temperature Graph](https://github.com/msvisser/remeha_home/assets/91673086/a458ce45-800d-443e-b81e-e97763103add)

Thanks for looking into this,
Peter

**Comment by msvisser** [comment] 2023-11-19 15:04
Hi Peter,

We are taking the water temperature information from the API as it is supplied to us, so it should update every minute when an update is requested. Either the API requests are failing, which you should see as the device becoming unavailable, or the temperature is simply reported like this by the API.

Michiel

**Comment by vharten** [comment] 2023-11-20 20:23
Hi,

 

I think the issue is in the API, since all other values are valid.

 

Besides that, I’ve had two times in 3 months that the device became unavailable, any way to discover the root cause?

 

Peter

 

Van: Michiel Visser ***@***.***> 
Verzonden: zondag 19 november 2023 16:05
Aan: msvisser/remeha_home ***@***.***>
CC: vharten ***@***.***>; Author ***@***.***>
Onderwerp: Re: [msvisser/remeha_home] Water temperature not consistently updated (Issue #39)

 

Hi Peter,

We are taking the water temperature information from the API as it is supplied to us, so it should update every minute when an update is requested. Either the API requests are failing, which you should see as the device becoming unavailable, or the temperature is simply reported like this by the API.

Michiel

**Comment by francesco-cambiaso** [comment] 2023-12-07 12:02
@vharten I'm experiencing looong delays in the hot water temperature updates as well, both with this HA integration and with the official mobile app. I use the De Dietrich Smart app that uses the same APIs.
The hot water temperature that I read from the thermostats is always up to date, so I'm quite sure that the issue is in the BDR Thermea cloud backend.

**Comment by msvisser** [comment] 2023-12-08 19:39
I'm pretty sure this is an issue on the cloud side and not with the integration, so I'm closing this issue for now.

**Closed by msvisser** 2023-12-08 19:39 UTC
